### ISSUE TITLE
关于clientHeight不变发导致的loadmore不触发

### ISSUE THREAD

**Issue by juanita-deng** [AwesomeDevin/vue-waterfall2#108]
如果直接是个大盒子里加载瀑布流事件估计会没有这个问题,但是作者忽略了那种盒子里再嵌套盒子局部做瀑布流的情况,会导致clientHeight不更新,导致loadmore不触发.看了下源码是因为clientHeight处理的有问题,于是改了这行就可以了
![image](https://user-images.githubusercontent.com/59787261/130165026-c2426940-585f-4ed3-b77e-380ba63e928f.png)
目前只发现安卓机是这样,ios正常

**Comment by lushengyunzuo** [comment]
我试了一下还是不可以

**Comment by liucjuan** [comment]
![image](https://user-images.githubusercontent.com/6970655/178975266-bfd6ed25-077d-4692-8b21-127782fe1d13.png)

试一下这样

**Comment by AwesomeDevin** [comment]
后续类似问题可以更新到最新版并指定height试试
