### ISSUE TITLE
vue2使用keep-alive包裹router-view，router-view内切换多个瀑布流实例，会出现异常：如A瀑布流切换至B瀑布流，再从B瀑布流切换会A瀑布流，此时，A瀑布流上拉加载失效

### ISSUE THREAD

**Issue by HOUSHENGREN** [AwesomeDevin/vue-waterfall2#109]

**Comment by shaguo666** [comment]
我也遇到了这个问题。。。。不知道怎么解决

**Comment by HOUSHENGREN** [comment]
项目如何允许，把keep-alive去掉；或者试下给每个water-fall唯一的key值

**Comment by shaguo666** [comment]
> 项目如何允许，把keep-alive去掉；或者试下给每个water-fall唯一的key值

keep-alive不能去；加key值是指直接在组件上加key吗，那样也不行

**Comment by shaguo666** [comment]
请问你有解决这个bug吗，还是说使用了其他瀑布流组件

**Comment by HOUSHENGREN** [comment]
我是直接去掉keep-alive了

**Comment by shaguo666** [comment]
> 我是直接去掉keep-alive了

好吧，谢谢
