### ISSUE TITLE
过渡效果似乎会报错

### ISSUE THREAD

**Issue by cykcykcykcyk** [AwesomeDevin/vue-waterfall2#11]
红字报错如下
`vue.runtime.esm.js?2b0e:619 [Vue warn]: Property or method "isTransition" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Waterfall> at node_modules/vue-waterfall2/waterfall.vue
       <CubeScroll> at node_modules/cube-ui/src/components/scroll/scroll.vue
         <Mall> at src/views/Mall.vue
           <Index> at src/views/Index.vue
             <App> at src/App.vue
               <Root>`

不知道是为什么

**Comment by cykcykcykcyk** [comment]
但是 重新运行以后就又不会了

**Comment by AwesomeDevin** [comment]
现在是没问题了吗
