### ISSUE TITLE
好像会出现数据丢失问题,我滚动加载的时候llist数据有部分没渲染处理,去掉插件包裹就会渲染出来

### ISSUE THREAD

**Issue by zhoujiaxu2014** [AwesomeDevin/vue-waterfall2#115]
目前还没找到什么问题

**Comment by AwesomeDevin** [comment]
有没有可能是图片链接的问题呢

**Comment by AyerCai** [comment]
我也出现了这个问题，请问解决了吗，有时候能渲染，但大多数时候数据缺失

**Comment by liuhangz1** [comment]
原因：vue2.xx的时候  watch 在拷贝数组对象时，不会保留备份，newVal 和oldVal 都指向同一个对象；而此框架在监听data时，使用了newValue 和oldVal值来判断加载，导致在切换list 数据时，第一个元素会丢失
解决方式=》主动清空组件的list 和loadindex, 为组件ref = waterfall
this.refs.waterfall.data = []
this.refs.loadeIndex = 0
