### ISSUE TITLE
如何添加占位图片

### ISSUE THREAD

**Issue by smalike** [AwesomeDevin/vue-waterfall2#129]
等待图片加载完成后显示，页面会有短暂的空白。如何添加默认的占位图呢？

**Comment by AwesomeDevin** [comment]
可以让图片资源尽量小点吧，压缩一下，因为需要获取图片属性，图片过大会影响体验，占位图的话，可以试试条件渲染，你可以针对图片做个预加载，预加载完成的图片才展示。

**Comment by smalike** [comment]
怎么给占位设置高宽呢？我是想在图片加载的时候占位撑起页面。可是现在看组件，貌似是图片加载完才显示到页面上。

**Comment by AwesomeDevin** [comment]
> 怎么给占位设置高宽呢？我是想在图片加载的时候占位撑起页面。可是现在看组件，貌似是图片加载完才显示到页面上。

宽度是可以设置的，高度没发设置，是自适应的，这个组件的优点就是支持宽高、自适应，不需要设置图片宽高

**Comment by smalike** [comment]
不设置图片宽高最大的问题就是要等到图片加载完页面的元素才能显示出来，这样会很慢。某个图片一旦超时那就是灾难性的。

**Comment by AwesomeDevin** [comment]
> 不设置图片宽高最大的问题就是要等到图片加载完页面的元素才能显示出来，这样会很慢。某个图片一旦超时那就是灾难性的。
超时的话，这个item就不会被展示
