### ISSUE TITLE
this.$waterfall.forceUpdate()失效

### ISSUE THREAD

**Issue by 1340145680** [AwesomeDevin/vue-waterfall2#131]
![image](https://user-images.githubusercontent.com/91125707/197600954-fe710b55-a673-49ad-a0f1-c56992afb45e.png)
数据变化了 this.$waterfall.forceUpdate();一直不起作用
![image](https://user-images.githubusercontent.com/91125707/197601196-372a163c-e3f5-4d65-8d47-ec343d7159c6.png)

**Comment by AwesomeDevin** [comment]
希望可以提供一个demo，理论上是可以监听到数据变化的，不需要执行forceupdate

**Comment by wmhh1129** [comment]
并不能监听到数据变化，单纯切换:data里面的值的时候
