### ISSUE TITLE
如果滚动加载loadmore时，新增数据diff无法大于max是不是会导致无法再次加载？

### ISSUE THREAD

**Issue by LikeMJ** [AwesomeDevin/vue-waterfall2#140]
loadmore事件只有在diff < max时候会触发，同时会修改loadmore为false，当新增数据无法大于max时，loadmore永远不会被设置为true？

**Comment by AwesomeDevin** [comment]
理论上分页内容不能少于一屏，目前还没有遇到少于一屏的业务场景，如果是新增数据达不到触发loadmore的距离，可以尝试修改loadDistance参数

**Comment by shuishan2025** [comment]
还有一种方式，视情况使用，增加一页的条数，比如原来pageSize=10，改成20。
