### ISSUE TITLE
改变窗口宽度会导致重复图片出现

### ISSUE THREAD

**Issue by huhan-123** [AwesomeDevin/vue-waterfall2#146]
我在浏览器中打开了含有瀑布流图片的网页，f12打开控制台后手动拖动窗口，有重复图片会添加到瀑布流中

**Comment by AwesomeDevin** [comment]
能提供一个demo吗，我试了一下之前写的demo，不会有这个问题

**Comment by huhan-123** [comment]
<template>
  <div >
      <waterfall :col="4" :data="images" :gutterWidth="7" ref="waterfallRef" class="w-full">
        <div class="mb-2" v-for="(item, index) in images" :key="index">
          <img v-if="item.imageUrl" :src="item.imageUrl"
               class="w-full h-auto block object-cover rounded-lg cursor-pointer"/>
        </div>
      </waterfall>
  </div>
</template>

<script setup>

import { ref} from "vue";

const images = ref([
  {
    "imageId": "....",
    "imageUrl": "...."
  },
....
])

const waterfallRef = ref(null)
</script>
我写了个demo，和在项目中的行为不一样，不过也有问题，这个demo的问题是改变窗口大小，瀑布流不会重新resize

**Comment by huhan-123** [comment]
```vue
<template>
  <div >
      <waterfall :col="4" :data="images" :gutterWidth="7" ref="waterfallRef" class="w-full">
        <div class="mb-2" v-for="(item, index) in images" :key="index">
          <img v-if="item.imageUrl" :src="item.imageUrl"
               class="w-full h-auto block object-cover rounded-lg cursor-pointer"/>
        </div>
      </waterfall>
  </div>
</template>

<script setup>

import { ref} from "vue";

const images = ref([
  {
    "imageId": "....",
    "imageUrl": "...."
  },
  .....
])

const waterfallRef = ref(null)
</script>

```

**Comment by huhan-123** [comment]
写了个demo，同样的代码，在我实际的项目中行为是拖动窗口，有重复图片会添加到瀑布流中，但是在demo中行为是拖动窗口，瀑布流不会重新渲染

**Comment by AwesomeDevin** [comment]
项目中有监听resize吗

**Comment by huhan-123** [comment]
有，但是我的监听函数并没有修改瀑布流的数据或者布局

**Comment by AwesomeDevin** [comment]
看一下data的赋值方式？是不是resize修改了data, 这时瀑布流数据就重复了

**Comment by huhan-123** [comment]
我用vue插件看数据是没有重复的

**Comment by AwesomeDevin** [comment]
拼接数据的时候看一下你的赋值方式？使用concat赋值试试， https://github.com/AwesomeDevin/vue-waterfall2/issues/115 有可能类似这个问题
