### ISSUE TITLE
waterfall loadmore不触发

### ISSUE THREAD

**Issue by pocketChao** [AwesomeDevin/vue-waterfall2#19]
![屏幕快照 2019-09-02 下午2 08 46](https://user-images.githubusercontent.com/21028807/64093514-40a1bb00-cd8b-11e9-8e63-9010d92e23a1.png)

**Comment by AwesomeDevin** [comment]
@pocketChao  应该是内容高度不够所以没有触发

**Comment by pocketChao** [comment]
> @pocketChao 应该是内容高度不够所以没有触发

需要给waterfall 设置高度吗  我这里已经拉到底啦
![屏幕快照 2019-09-03 下午1 38 44](https://user-images.githubusercontent.com/21028807/64146607-30074880-ce50-11e9-8caa-3dad2c0bba0b.png)
![屏幕快照 2019-09-03 下午1 38 29](https://user-images.githubusercontent.com/21028807/64146609-33023900-ce50-11e9-96c6-afc5dc6f057f.png)
![屏幕快照 2019-09-03 下午1 38 18](https://user-images.githubusercontent.com/21028807/64146612-35649300-ce50-11e9-91fe-3fc54a7182e7.png)

**Comment by FrankRoc** [comment]
同样的问题...查找中

**Comment by AwesomeDevin** [comment]
> 同样的问题...查找中
> 复制案例代码都不行..代码中并未找到要设置容器高度的片段.

不能给容器设置高度，组件监听的是页面的滚动,设置高度滚动的就是容器

**Comment by AwesomeDevin** [comment]
https://juejin.im/post/5bee6c4be51d4536c03fc519     有相同问题的同学可以看一下这里,组件监听的是页面的滚动，所以不能给容器设置高度,html也不行

**Comment by StringKe** [comment]
![image](https://user-images.githubusercontent.com/31089228/64223696-7ff51680-cf07-11e9-8e07-9308d6317a0f.png)
我是上方需要固定下方滚动的。。。。如果需要不固定高度这要这么做....我这种布局方式所有地方的高度和宽度基本上都是有固定的.......

**Comment by AwesomeDevin** [comment]
> ![image](https://user-images.githubusercontent.com/31089228/64223696-7ff51680-cf07-11e9-8e07-9308d6317a0f.png)
> 我是上方需要固定下方滚动的。。。。如果需要不固定高度这要这么做....我这种布局方式所有地方的高度和宽度基本上都是有固定的.......

可以设置高度，但是不能允许容器滚动,页面滚动才能监听，如果容器必须滚动，可以尝试自己实现一个loadmore

**Comment by StringKe** [comment]
> > 我是上方需要固定下方滚动的。。。。如果需要不固定高度这要这么做....我这种布局方式所有地方的高度和宽度基本上都是有固定的.......
> 
> 可以设置高度，但是不能允许容器滚动,页面滚动才能监听，如果容器必须滚动，可以尝试自己实现一个loadmore

![image](https://user-images.githubusercontent.com/31089228/64224741-3d353d80-cf0b-11e9-882a-7718bf5dda9d.png)
是在loading设置高度还是vue-watefall

**Comment by AwesomeDevin** [comment]
> > > 我是上方需要固定下方滚动的。。。。如果需要不固定高度这要这么做....我这种布局方式所有地方的高度和宽度基本上都是有固定的.......
> > 
> > 
> > 可以设置高度，但是不能允许容器滚动,页面滚动才能监听，如果容器必须滚动，可以尝试自己实现一个loadmore
> 
> ![image](https://user-images.githubusercontent.com/31089228/64224741-3d353d80-cf0b-11e9-882a-7718bf5dda9d.png)
> 是在loading设置高度还是vue-watefall

按需求来，都可以设置高度，只是组件提供的loadmore无法监听容器滚动，监听的是页面的滚动

**Comment by FrankRoc** [comment]
> > 我是上方需要固定下方滚动的。。。。如果需要不固定高度这要这么做....我这种布局方式所有地方的高度和宽度基本上都是有固定的.......
> 
> 可以设置高度，但是不能允许父容器滚动，如果父容器必须滚动，可以尝试自己实现一个loadmore

给waterfall的父级设置为不允许滚动,给waterfall父级的父级设置了滚动,依旧不行...监听的是html的滚动吗?

**Comment by AwesomeDevin** [comment]
@FrankRoc  监听的是window的滚动事件

**Comment by StringKe** [comment]
@AwesomeDevin 设置的双列加载后是单列该如何刷新？我forceupdate还是单列

**Comment by AwesomeDevin** [comment]
> @AwesomeDevin 设置的双列加载后是单列该如何刷新？我forceupdate还是单列

你好 另起1个issue吧，最好贴一下代码

**Comment by pocketChao** [comment]
看了下并没有父组件设置overflow, 有解决的么

**Comment by pocketChao** [comment]
![屏幕快照 2019-09-10 下午5 16 24](https://user-images.githubusercontent.com/21028807/64601114-eb028980-d3ee-11e9-9dbe-cc63f2273a55.png)
![屏幕快照 2019-09-10 下午5 16 34](https://user-images.githubusercontent.com/21028807/64601117-eb028980-d3ee-11e9-8992-f80c06f34cf4.png)
这是我的滚动数据

**Comment by AwesomeDevin** [comment]
#28 已更新loadmore特性
