### ISSUE TITLE
作者您好，我使用了分两页显示，在使用过程中，偶尔刷新会出现只有一列的问题

### ISSUE THREAD

**Issue by sroctop** [AwesomeDevin/vue-waterfall2#20]
作者您好，我使用了分两页显示，在使用过程中，偶尔刷新会出现只有一列的问题。另外一列，从DOM上看，内容为空，如果继续下拉的话，内容仅出现在第一列，第二列一直没有内容。刷新一下页面才能显示第二列。

![大鹏博客](http://pxhpqcwhp.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720190908095126.png)

**Comment by AwesomeDevin** [comment]
> 作者您好，我使用了分两页显示，在使用过程中，偶尔刷新会出现只有一列的问题。另外一列，从DOM上看，内容为空，如果继续下拉的话，内容仅出现在第一列，第二列一直没有内容。刷新一下页面才能显示第二列。
> 
> ![大鹏博客](https://camo.githubusercontent.com/088d2fd47e66e294fa93ce582ad095ab3fef1919/687474703a2f2f7078687071637768702e626b742e636c6f7564646e2e636f6d2f515125453525394225424525453725383925383732303139303930383039353132362e706e67)

请问版本号是多少

**Comment by sroctop** [comment]
"vue-waterfall2": "^1.8.20",

**Comment by AwesomeDevin** [comment]
> "vue-waterfall2": "^1.8.20",
你好，vue的版本号呢,我这边暂时还没复现出来

**Comment by sroctop** [comment]
{
  "name": "vue_ts",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --open",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "start": "vue-cli-service serve --mode production --open"
  },
  "dependencies": {
    "core-js": "^2.6.5",
    "js-cookie": "^2.2.0",
    "less": "^3.10.2",
    "less-loader": "^5.0.0",
    "super-touch": "^0.0.5",
    "vant": "^2.1.3",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-growingio": "^1.0.8",
    "vue-property-decorator": "^8.1.0",
    "vue-pull-refresh": "^0.2.7",
    "vue-router": "^3.0.3",
    "vue-waterfall2": "^1.8.20",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@uplus/uplus-api": "^2.5.5",
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-plugin-typescript": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "axios": "^0.19.0",
    "babel-plugin-import": "^1.12.0",
    "filemanager-webpack-plugin": "^2.0.5",
    "style-resources-loader": "^1.2.1",
    "ts-import-plugin": "^1.6.1",
    "typescript": "^3.4.3",
    "vue-cli-plugin-style-resources-loader": "^0.1.3",
    "vue-template-compiler": "^2.6.10",
    "webpack-zip-plugin": "^0.1.6",
    "weixin-js-sdk": "^1.4.0-test"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "HomePage": "http://www.qzroc.com",
  "anthor": "roc"
}

**Comment by sroctop** [comment]
> > "vue-waterfall2": "^1.8.20",
> > 你好，vue的版本号呢,我这边暂时还没复现出来
vue版本为2.6.10

**Comment by AwesomeDevin** [comment]
...我没有复现出你的这个问题

**Comment by zqzq1217** [comment]
大哥您怎么解决的这个bug呢？？？跪求大佬指点
