### ISSUE TITLE
发现源码内的scrollHeight为undefined导致loadmore方法不触发

### ISSUE THREAD

**Issue by pocketChao** [AwesomeDevin/vue-waterfall2#22]
![屏幕快照 2019-09-16 下午2 00 35](https://user-images.githubusercontent.com/21028807/64936858-93e73380-d88a-11e9-9af7-07e5e5b637fe.png)
![屏幕快照 2019-09-16 下午2 01 26](https://user-images.githubusercontent.com/21028807/64936859-96498d80-d88a-11e9-9b70-735697104acf.png)

**Comment by AwesomeDevin** [comment]
#28 已更新loadmore特性
