### ISSUE TITLE
scorllheight一直未变导致loadmore不触发  请问大家知道是什么原因么

### ISSUE THREAD

**Issue by pocketChao** [AwesomeDevin/vue-waterfall2#23]
![屏幕快照 2019-09-16 下午2 06 47](https://user-images.githubusercontent.com/21028807/64937048-47e8be80-d88b-11e9-86ac-4e12f3edbea3.png)
![屏幕快照 2019-09-16 下午2 06 57](https://user-images.githubusercontent.com/21028807/64937053-49b28200-d88b-11e9-869a-bd4f8ef12989.png)

**Comment by pocketChao** [comment]
![屏幕快照 2019-09-16 下午2 08 12](https://user-images.githubusercontent.com/21028807/64937135-aa41bf00-d88b-11e9-9894-fb1376c267ab.png)
![屏幕快照 2019-09-16 下午2 09 17](https://user-images.githubusercontent.com/21028807/64937140-ac0b8280-d88b-11e9-9c0e-7513af61652e.png)
大概是这样一个结构

**Comment by pocketChao** [comment]
scrollheight不是这么取么
![屏幕快照 2019-09-16 下午2 16 58](https://user-images.githubusercontent.com/21028807/64937405-b8dca600-d88c-11e9-9a0d-4ede359ef324.png)

**Comment by AwesomeDevin** [comment]
滚动的会不会是div容器，不是window

**Comment by JustGogoing** [comment]
我现在也是这个问题, 滚动的是容器而不是window

**Comment by pocketChao** [comment]
> 滚动的会不会是div容器，不是window

好像Vue的虚拟dom用document会很诡异  我没设置容器的高度也不行 用this.$el就好用😆

**Comment by pocketChao** [comment]
![屏幕快照 2019-09-17 下午4 54 23](https://user-images.githubusercontent.com/21028807/65026858-ecdac880-d96b-11e9-88a5-b3dca85dc708.png)
![屏幕快照 2019-09-17 下午4 54 53](https://user-images.githubusercontent.com/21028807/65026859-ef3d2280-d96b-11e9-865d-54f07eaff1f4.png)
这是大概的结构   waterfall 放在pullrefresh中  能看出来大概的原因么  刚转前端 css很烂不好意思哈

**Comment by AwesomeDevin** [comment]
#28 已更新loadmore特性

**Comment by juanita-deng** [comment]
请问解决了吗?我也是遇到同样的问题,在电脑模拟器上是正常的,但放到手机上就一直scrollHeight不变,导致loadMore不触发
