### ISSUE TITLE
所有图片都加载在第一列

### ISSUE THREAD

**Issue by FengGod** [AwesomeDevin/vue-waterfall2#25]
<waterfall :col='col' :width="itemWidth" :gutterWidth="gutterWidth"  :data="picBox">
                                    <template >
                                        <div class="cell-item" v-for="(item,index) in picBox" :key="index">
                                        <img  :src="item.ImgUrl" /> 
                                        <div class="item-body">
                                            <div class="item-desc">{{item.CellTypeHistory}}</div>
                                        </div>
                                    </div>
                                    </template>
                                    </waterfall>

**Comment by FengGod** [comment]
![image](https://user-images.githubusercontent.com/39045730/66372048-9ba47e80-e9d7-11e9-9d13-952e0a881553.png)

**Comment by FengGod** [comment]
![image](https://user-images.githubusercontent.com/39045730/66372132-d8707580-e9d7-11e9-91b6-073fe6e36688.png)

**Comment by AwesomeDevin** [comment]
你好，可以的话麻烦提供一份完整一点的代码吧，这样不太好排查原因~

**Comment by FengGod** [comment]
[demo.docx](https://github.com/AwesomeDevin/vue-waterfall2/files/3705281/demo.docx)

**Comment by AwesomeDevin** [comment]
貌似没有用到我这个组件..

**Comment by FengGod** [comment]
在我这个项目里面图片随机出现瀑布流，这是出现的三种情况，我现在也给整蒙了。
![image](https://user-images.githubusercontent.com/39045730/66455257-c0aef500-ea9c-11e9-96e1-e1a2aa640ea9.png)
![image](https://user-images.githubusercontent.com/39045730/66455297-e20fe100-ea9c-11e9-87db-e671df2f6d63.png)
![image](https://user-images.githubusercontent.com/39045730/66455335-0b307180-ea9d-11e9-9b22-966d84c742bf.png)

**Comment by AwesomeDevin** [comment]
是随机的吗,看一下你的package.json

**Comment by FengGod** [comment]
{
  "name": "vue-admin-template",
  "version": "4.2.1",
  "description": "A vue admin template with Element UI & axios & iconfont & permission control & lint",
  "author": "Pan <panfree23@gmail.com>",
  "license": "MIT",
  "scripts": {
    "dev": "vue-cli-service serve",
    "build:prod": "vue-cli-service build",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node build/index.js --preview",
    "lint": "eslint --ext .js,.vue src",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml"
  },
  "dependencies": {
    "axios": "0.18.0",
    "element-ui": "2.11.0",
    "iview": "^3.4.2",
    "js-cookie": "2.2.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "openseadragon": "^2.4.1",
    "path-to-regexp": "2.4.0",
    "vue": "2.6.10",
    "vue-openseadragon": "^0.1.2",
    "vue-router": "3.0.6",
    "vue-waterfall2": "^1.8.20",
    "vuex": "3.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.0.0",
    "@babel/register": "7.0.0",
    "@vue/cli-plugin-babel": "3.6.0",
    "@vue/cli-plugin-eslint": "3.6.0",
    "@vue/cli-plugin-unit-jest": "3.6.3",
    "@vue/cli-service": "3.6.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "^9.5.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "23.6.0",
    "chalk": "2.4.2",
    "connect": "3.6.6",
    "eslint": "5.15.3",
    "eslint-plugin-vue": "5.2.2",
    "html-webpack-plugin": "3.2.0",
    "mockjs": "1.0.1-beta3",
    "node-sass": "^4.9.0",
    "runjs": "^4.3.2",
    "sass-loader": "^7.1.0",
    "script-ext-html-webpack-plugin": "2.1.3",
    "script-loader": "0.7.2",
    "serve-static": "^1.13.2",
    "svg-sprite-loader": "4.1.3",
    "svgo": "1.2.2",
    "vue-template-compiler": "2.6.10",
    "vue-waterfall-easy": "^2.4.4"
  },
  "engines": {
    "node": ">=8.9",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

**Comment by AwesomeDevin** [comment]
有报错吗?我试了一下vue版本2.6.10 没问题

**Comment by FengGod** [comment]
没有报错，我使用你这个插件，图片流是随机三种情况，使用vue-waterfall-easy这个插件，图片流要不是正常，要不是都叠在一起，我都快整蒙了，也不知道问题出在哪里。是不是我这个vue-admin-template框架不兼容？

**Comment by AwesomeDevin** [comment]
我试试vue-admin-template，没试验过

**Comment by FengGod** [comment]
感谢，如果正常的话，只有请大哥帮我远程瞧瞧了，项目卡在这里了。

**Comment by AwesomeDevin** [comment]
我这边是正常的..

**Comment by FengGod** [comment]
咱们怎么远程帮我瞄一下我的代码？

**Comment by AwesomeDevin** [comment]
在公司不太方面，只能回家远程

**Comment by FengGod** [comment]
大哥你能把你vue-admin-template的demo发我看看不？189973341@qq.com感谢！

**Comment by AwesomeDevin** [comment]
已发

**Comment by FengGod** [comment]
收到，正在对比逐步排查。

**Comment by FengGod** [comment]
经过多次测试，我发现图片来源是从data中获取静态来源的话，刷新图片样式没有问题。但是，我从后台动态获取图片来源，每次刷新都会导致图片的样式出现那三种变化。
[test_demo.docx](https://github.com/AwesomeDevin/vue-waterfall2/files/3706330/test_demo.docx)

**Comment by AwesomeDevin** [comment]
好  我排查一下原因

**Comment by FengGod** [comment]
是不是和Vue的生命周期有相关影响？

**Comment by AwesomeDevin** [comment]
beforeCreate里的逻辑处理  放到 mounted 试试

**Comment by FengGod** [comment]
奇了怪了，我放在mounted里面数据好像都没经过插件处理直接自己列出来生成一列。我这个项目好奇怪啊。我们用静态源测试过，同框架异步测试过，Vue生命周期也测试了，问题还可能出现在什么地方？

**Comment by AwesomeDevin** [comment]
试试v1.8.21

**Comment by FengGod** [comment]
尝试了新版本，貌似没变化，还是老三种情况。我这边测试其他的图片还发现这样的一种情况，如果几张大小差不多的图片排列在第一行的话，那么基本上怎么刷新瀑布流都没啥问题，像我发的那种第一行图片大小差距比较大的话，刷新就会随机出现老三种情况。

**Comment by FengGod** [comment]
就是这种情况，每次刷新第一行的图片位置都会发生改变。
![image](https://user-images.githubusercontent.com/39045730/66549358-b6145e80-eb75-11e9-97c8-975aa0c79091.png)
但是，如果第一行的图片是这种大小差不多的话，怎么刷新他这个里面的图片位置都不会发生改变，样式也不会挂掉。
![image](https://user-images.githubusercontent.com/39045730/66549496-f5db4600-eb75-11e9-9051-be51288d3847.png)

**Comment by AwesomeDevin** [comment]
你的图片是http链接的吗，我试试？

**Comment by FengGod** [comment]
在相同的代码条件下，我将上面的两种图片源的图片都刷新50次测试。第一种图片源的瀑布流会随机发生之前的三种情况，但是下面的图片每次都是正常的瀑布流。

**Comment by FengGod** [comment]
是有时间限制的OSS链接，后台生成的。

**Comment by AwesomeDevin** [comment]
ok

**Comment by FengGod** [comment]
不过那个OSS链接的顺序是我手动添加的，可能与我上面的顺序不一样，不知道能不能测试得出来。

**Comment by AwesomeDevin** [comment]
你好，我这边找了宽高差很大的图片，还是没有复现出来..

**Comment by zqzq1217** [comment]
老哥我出现了偶发现象数据全部出现在右侧的一列里，跪求大哥

**Comment by bepure1234** [comment]
数据出现一列情况怎么解决，求大佬指点一下
