### ISSUE TITLE
v1.9.5 已支持div内监听滚动事件，并触发loadMore

### ISSUE THREAD

**Issue by AwesomeDevin** [AwesomeDevin/vue-waterfall2#28]
✅ height为空监听的是window的滚动事件，不为空则监听容器滚动

**Comment by AwesomeDevin** [comment]
欢迎同学们继续提issue,谢谢支持

**Comment by eep2019** [comment]
为什么不能触发loadmore，已经滚动到底部了。上面三分之一是其他内容，剩下的才是waterfall

**Comment by geesmart** [comment]
解决了我的问题

**Comment by geesmart** [comment]
测试，loadMore 还是不能触发呢，经测试  v1.9.5 和 v1.9.6 

 @loadmore="loadmore"

**Comment by SAO-Asuna** [comment]
你好，我这边设置了loadmore但是滚动到底 没有触发 方法，请问是什么原因呢？

**Comment by SAO-Asuna** [comment]
就是获取 scrollHeight 为 0

**Comment by Fengmaybe** [comment]
怎么知道是window滚动还是div容器内部滚动呢？？我没将外层div高度做设定，应该就是监听window的滚动事件吧。为啥loadmore就是不执行呢？增加了height属性后就可以加载。可是我并不知道具体的height要设置为多少？怎么办

**Comment by zqzq1217** [comment]
因为你#app，body，html里面写了height：100%，所以一直会出现scrollHeight，这有篇文章可以去看一下[https://blog.csdn.net/weixin_45835771/article/details/105759524](url)

**Comment by AwesomeDevin** [comment]
> 怎么知道是window滚动还是div容器内部滚动呢？？我没将外层div高度做设定，应该就是监听window的滚动事件吧。为啥loadmore就是不执行呢？增加了height属性后就可以加载。可是我并不知道具体的height要设置为多少？怎么办

看是否还有其它同期设置了overflow:auto

**Comment by zqzq1217** [comment]
大佬可以加您一个联系方式吗

**Comment by dfzdfz** [comment]
@loadmore只执行一次

**Comment by dfzdfz** [comment]
@loadmore只执行一次   麻烦可以提供下解决方法吗

**Comment by AwesomeDevin** [comment]
> @loadmore只执行一次 麻烦可以提供下解决方法吗

1. 可以先排查一下，页面内是否有其它属性设置了overflow:auto属性,有其它容器滚动的话，就监听不到window的滚动了
2.已知高度的话, 可以尝试添加height属性

**Comment by DDQH** [comment]
您好，我想问一下分成两列的，顺序会被打乱。比如正确的是1,2 | 3,4 | 5,6 ,第一次进入页面也是正常顺序的，但是刷新几次就会出现1,2 | 3,4 | 6,5（这里6到5前面了） | 7,8 也有可能是10,9这样，反正有时顺序正常，不正常的情况多一些。
