### ISSUE TITLE
数据为什么都会跑 slot-box 这个里面，不在.vue-waterfall-column里面

### ISSUE THREAD

**Issue by shaoqingWeb** [AwesomeDevin/vue-waterfall2#3]
![1546414008 1](https://user-images.githubusercontent.com/29299959/50583174-b2470380-0ea2-11e9-85f4-7482ecd2cc45.png)

**Comment by AwesomeDevin** [comment]
请问vue的版本号是多少，应该是vue 的版本过低

**Comment by AwesomeDevin** [comment]
请问是否报错

**Comment by AwesomeDevin** [comment]
这个问题我排查一下
