### ISSUE TITLE
Property or method "height" is not defined

### ISSUE THREAD

**Issue by dolphinfine** [AwesomeDevin/vue-waterfall2#30]
` Property or method "height" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`
一进来就报错

**Comment by dolphinfine** [comment]
降级到1.8.22好了

**Comment by dolphinfine** [comment]
锁定版本感觉不太好。。。

**Comment by AwesomeDevin** [comment]
感谢反馈  我修一下
