### ISSUE TITLE
dom.querySelectorAll is not a function

### ISSUE THREAD

**Issue by milaotou** [AwesomeDevin/vue-waterfall2#33]
waterfall里面放了不相关的内容，但都需要下来，报dom.querySelectorAll is not a function是什么原因呢？

**Comment by AwesomeDevin** [comment]
你好，不相关的内容是指？

**Comment by milaotou** [comment]
当waterfall 组件包含header区域，banner以及中间的区域就会报错，当waterfall 只包含瀑布流的图片就没有问题。

**Comment by AwesomeDevin** [comment]
修了一下，有空可以更新到最新版试试

**Comment by milaotou** [comment]
不报错了，但会影响header区域的样式，把需要瀑布流的内容放到vue-waterfall-column里面去了，怎么放到slot-box里面呢

**Comment by AwesomeDevin** [comment]
有没有办法从布局上做改动，将非瀑布流的布局放到waterfall外

**Comment by AwesomeDevin** [comment]
不太清楚你的header/banner是什么，不太好排查😐

**Comment by milaotou** [comment]
就是头部信息，banner轮播图，想让整个页面都滑动
