### ISSUE TITLE
img展示是否支持自动裁剪？

### ISSUE THREAD

**Issue by cuixinxin4869** [AwesomeDevin/vue-waterfall2#37]
当图片是一张大长图，是否会截取中间一部分？ 还是根据图片宽100%，高自适应？？ 感谢回答

**Comment by cuixinxin4869** [comment]
![image](https://user-images.githubusercontent.com/57824338/69204770-db3bba00-0b82-11ea-8739-aac57593f81b.png)

**Comment by cuixinxin4869** [comment]
像第一张这样展示就很不友好，不知道有无什么好的解决方案？

**Comment by AwesomeDevin** [comment]
现在是宽度100%,高度自适应的方案,第一张图原图是怎样的？

**Comment by cuixinxin4869** [comment]
嗯，第一张是宽750*2000的，要是让前端做裁剪也不现实，除非服务端支持。咱们其实可以用background-image来实现，要比img友好些

**Comment by AwesomeDevin** [comment]
哈哈，那你可以改一下样式
