### ISSUE TITLE
height 未定义

### ISSUE THREAD

**Issue by blesstosam** [AwesomeDevin/vue-waterfall2#38]
<img width="1017" alt="WX20191123-130124@2x" src="https://user-images.githubusercontent.com/26403700/69473642-bbf69400-0df1-11ea-80f7-03b4365021a0.png">

**Comment by AwesomeDevin** [comment]
你好，请问vue版本号是多少

**Comment by blesstosam** [comment]
2.6.10

**Comment by AwesomeDevin** [comment]
尝试手动传height属性进去，有用吗

**Comment by AwesomeDevin** [comment]
可以看一下你的package.json文件吗

**Comment by AwesomeDevin** [comment]
可更新到1.9.5试试  height为空监听的是window的滚动事件，不为空则监听容器滚动

**Comment by blesstosam** [comment]
刚刚发的包吗？我之前是1.9.4

**Comment by AwesomeDevin** [comment]
是的

**Comment by blesstosam** [comment]
升级后，已经好了！谢谢你！反应很及时啊，方便加个微信吗？以后有机会多交流。我微信号805902285，或者我加你！

**Comment by AwesomeDevin** [comment]
可以  我加吧
