### ISSUE TITLE
手机上滑动不丝滑，很卡

### ISSUE THREAD

**Issue by cuixinxin4869** [AwesomeDevin/vue-waterfall2#40]
手机上滑动不丝滑，很卡，这个作者有好的解决方案？

**Comment by AwesomeDevin** [comment]
请问机型是？ 之前我做移动端需求的时候，体验还可以

**Comment by cuixinxin4869** [comment]
最外层container加了一个-webkit-overflow-scrolling: touch;就流畅了

**Comment by AwesomeDevin** [comment]
好，我这边优化一下, overflow-scrolling: touch; 似乎有兼容性问题？

**Comment by geesmart** [comment]
数据量多了后，第一次加载的时候，很卡，分段加载的时候，loadmore 不能加载，ps : v1.9.6 版本

**Comment by AwesomeDevin** [comment]
@geesmart  有设置高度吗

**Comment by geesmart** [comment]
@AwesomeDevin 感谢，我目前没有图片 div 里面嵌套了一个 ace editor 。目前我是用loadmore的方式加载的。用的 element-ui 的 v-infinite-scroll ，测试可以

<waterfall v-infinite-scroll="loadmore"

**Comment by AwesomeDevin** [comment]
额.. 不太明白现在是怎么使用的,希望可以给个demo 👏
