### ISSUE TITLE
引用了这个包，Uglify构建报错

### ISSUE THREAD

**Issue by chiuwingyan** [AwesomeDevin/vue-waterfall2#42]
引用了这个包后，Uglify构建的时候报错：

ERROR in app.js from UglifyJs
Unexpected token: punc «(» [app.js:555,6]

引用es5文件夹里面的话，var _waterfall = require('./waterfall.vue');
这个路径没写对

跪求大佬修复！！！

**Comment by AwesomeDevin** [comment]
更新到v1.9.6试试~
```js
import waterfall from 'vue-waterfall2'
```
这样写应该不会有这个问题吧,你是import es5目录下的index了吗
