### ISSUE TITLE
关于loadmore触发机制问题

### ISSUE THREAD

**Issue by forzenzhou** [AwesomeDevin/vue-waterfall2#46]
版本："vue-waterfall2": "^1.9.6"
问题描述：loadmore的触发机制让我有点费解，我在第一次进入页面的时候loadDistance写的很小，滚动部分在我页面下部分，应该达到触发条件，但是没有执行，我稍微把页面向下拖动一点就触发了，我想让页面已进入就触发loadmore怎么做呢？

**Comment by AwesomeDevin** [comment]
这一块，我晚点针对loadmore加上一个自否自动加载的配置项吧，目前建议进入页面的时候手动执行一次loadmore

**Comment by forzenzhou** [comment]
感谢回答,其实这个我后来加个开关就好了
