### ISSUE TITLE
搜索框点击搜索报错

### ISSUE THREAD

**Issue by forzenzhou** [AwesomeDevin/vue-waterfall2#47]
版本"vue-waterfall2": "^1.9.6"
问题描述：搜索框输入内容，点击搜索后调用接口，返回数据给data赋值报错;接口返回正确，打印赋值成功；
报错信息：[Vue warn]: Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."；
加了nextTick无效

**Comment by forzenzhou** [comment]
![image](https://user-images.githubusercontent.com/21830743/70864527-d86b9380-1f8d-11ea-9c28-398d138f1ff5.png)

**Comment by AwesomeDevin** [comment]
你好，麻烦提供一下vue版本号，另外这里模拟加载假数据会报错吗？

**Comment by forzenzhou** [comment]
晚上我看下版本,假数据我得试试

**Comment by forzenzhou** [comment]
"vue": "^2.6.10"
不调接口直接给赋值不会报错，但是点击搜索第一次没反应，但是可以打印出内容，第二次点击页面才显示数据

**Comment by forzenzhou** [comment]
![image](https://user-images.githubusercontent.com/21830743/70905098-05777f00-203e-11ea-986d-f12fce9d2d68.png)

**Comment by AwesomeDevin** [comment]
可以确定是组件的锅吗... 你这个情况我没复现出来

**Comment by forzenzhou** [comment]
晚上我在确定下

**Comment by AwesomeDevin** [comment]
👌
