### ISSUE TITLE
引用报错SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by hilanmiao** [AwesomeDevin/vue-waterfall2#48]
![image](https://user-images.githubusercontent.com/27052900/71577808-9404f980-2b30-11ea-8029-1f6a70a49ffb.png)

![image](https://user-images.githubusercontent.com/27052900/71577835-ab43e700-2b30-11ea-9e4d-c94c69e809f3.png)

安装的是1.9.6版本，环境是electron-vue
import 后出现如上图所示错误，请问有遇到过这种情况的吗？

**Comment by AwesomeDevin** [comment]
electron-vue 还没有试过...，是不是没有引入babel?看起来是语法报错

**Comment by hilanmiao** [comment]
> electron-vue 还没有试过...，是不是没有引入babel?看起来是语法报错

或许是有这个可能，应该就是编译问题，我先关了吧，有机会再试
