### ISSUE TITLE
有时候，会出现左边排了2个

### ISSUE THREAD

**Issue by eep2019** [AwesomeDevin/vue-waterfall2#51]
最后一个其实是可以排去右边的。是因为算高度没算对吗？

<img width="447" alt="WX20200116-153620@2x" src="https://user-images.githubusercontent.com/50366852/72503146-00446480-3876-11ea-8934-79b3ca9dbc2a.png">

**Comment by AwesomeDevin** [comment]
现在是先算出高度再渲染的，能排查出什么情况会出现这个问题吗

**Comment by Fengmaybe** [comment]
我也出现这个问题呢，最新的版本

**Comment by yigemajia** [comment]
@Fengmaybe 你得把图片的高度给它才行，就可以解决。
