### ISSUE TITLE
width,gutterWidth 数据更新问题

### ISSUE THREAD

**Issue by fangyu2017** [AwesomeDevin/vue-waterfall2#56]
整体视图宽度发生改变，更新width,gutterWidth 值，组件视图宽并未更新，作者能否可以加上这个功能

**Comment by AwesomeDevin** [comment]
```js
this.$waterfall.forceUpdate()   //forceUpdate
```
可以试一下这个api

**Comment by huziyang410** [comment]
width,gutterWidth变化时，组件内的width,gutterWidth不是动态改变的。我暂时通过改变col的值，触发宽度的重新渲染
