### ISSUE TITLE
移动端两列布局问题

### ISSUE THREAD

**Issue by Fengmaybe** [AwesomeDevin/vue-waterfall2#58]
使用后，每次接口数据50，发现最后都会网一边倾斜的，没有按照瀑布流布局，一边会多出很多。

[图片](https://imgsrc.com/image/swJr)

img使用普通的就没问题刚测试了。:src='img'  但是用：lazy-src='img' 就会出现以上图片问题，两边图片的不是瀑布流的，一边高一边低。

**Comment by AwesomeDevin** [comment]
好的，感谢反馈，这一块我看一下
