### ISSUE TITLE
已知图片搞定并进行预先加载时候优化显示效果？

### ISSUE THREAD

**Issue by StringKe** [AwesomeDevin/vue-waterfall2#60]
![image](https://user-images.githubusercontent.com/31089228/78321631-20471280-759f-11ea-913e-1b309d6b6fba.png)

这种情况如果优化呢？如果单纯的平均分列，无法有最佳的显示效果。

加载的图片中有一个 宽高比列为  1:10 的图片，会导致单独一列特别长，在已知图片宽高的情况下，应当自动适配宽高调整每列的项。

**Comment by AwesomeDevin** [comment]
目前的方案并不是通过平均来实现布局的哦，是否可以实现一个codesandbox代码，我这边看一下
