### ISSUE TITLE
设置三列布局，刷新浏览器时而排版正常，时而只有一列

### ISSUE THREAD

**Issue by lengbing95** [AwesomeDevin/vue-waterfall2#62]
设置三列布局，刷新浏览器时而排版正常，时而只有一列

**Comment by zqzq1217** [comment]
老哥你解决了吗，跪求大佬指点

**Comment by AwesomeDevin** [comment]
> 老哥你解决了吗，跪求大佬指点

这个问题我要复现在才行，最近工作有点忙，下班试试

**Comment by xts871722743** [comment]
刷新然后不等渲染  直接去别的页面  再回来就是一列

**Comment by zqzq1217** [comment]
您怎么解决了吗？怎么解决的？我想过延时或者等dom渲染完成后再去跳转页面但是也好像并不怎么好使

**Comment by xts871722743** [comment]
> 您怎么解决了吗？怎么解决的？我想过延时或者等dom渲染完成后再去跳转页面但是也好像并不怎么好使

我也刚被提的bug  研究下吧

**Comment by zqzq1217** [comment]
> > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> 
> 我也刚被提的bug研究下吧



> > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> 
> 我也刚被提的bug研究下吧
您要是解决了麻烦老哥分享一下解决经验

**Comment by xts871722743** [comment]
> > > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> > 
> > 
> > 我也刚被提的bug研究下吧
> 
> > > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> > 
> > 
> > 我也刚被提的bug研究下吧
> > 您要是解决了麻烦老哥分享一下解决经验

我这边的情况是刚进入瀑布流的页面，立刻快速切换到别的页面，导致源代码里面的获取高度失败，所以那里的判断出现问题了。就造成了一列。由于我的页面是keep-alive的，所以我在activated里面加了他的这个强制刷新。this.$waterfall.forceUpdate()   //forceUpdate   然后就解决了

**Comment by zqzq1217** [comment]
> > > > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> > > 
> > > 
> > > 我也刚被提的bug研究下吧
> > 
> > 
> > > > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> > > 
> > > 
> > > 我也刚被提的bug研究下吧
> > > 您要是解决了麻烦老哥分享一下解决经验
> 
> 我这边的情况是刚进入瀑布流的页面，立即快速切换到别的页面，导致源代码里面的获取高度失败，所以那里的判断出现问题了。就造成了一列。由于我的页面是keep- alive的，所以我在激活里面加了他的这个强制刷新。this。$ waterfall.forceUpdate（）// forceUpdate然后就解决了

老哥我能说我也是这么解决的嘛？还有更好的办法吗

**Comment by xts871722743** [comment]
> > > > > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> > > > 
> > > > 
> > > > 我也刚被提的bug研究下吧
> > > 
> > > 
> > > > > 您怎么解决了吗？怎么解决的？我想过交替或等dom渲染完成后再去替换页面但是也好像并不怎么好使
> > > > 
> > > > 
> > > > 我也刚被提的bug研究下吧
> > > > 您要是解决了麻烦老哥分享一下解决经验
> > 
> > 
> > 我这边的情况是刚进入瀑布流的页面，立即快速切换到别的页面，导致源代码里面的获取高度失败，所以那里的判断出现问题了。就造成了一列。由于我的页面是keep- alive的，所以我在激活里面加了他的这个强制刷新。this。$ waterfall.forceUpdate（）// forceUpdate然后就解决了
> 
> 老哥我能说我也是这么解决的嘛？还有更好的办法吗

目前没找到别的方式  不获取高度就是没法排序 或者改成定位的瀑布流

**Comment by W-ChenAMG** [comment]
我加this.$waterfall.forceUpdate()  也不好使的，应该咋整

**Comment by xuekesong** [comment]
> 我加this.$waterfall.forceUpdate() 也不好使的，应该咋整

我也出现这种情况了，能说一下你最后怎么解决的吗

**Comment by 17686419746** [comment]
有一种比较low的办法就是你比对两列的数据如果某一列的数据比另外一列数据多三个以上从新调用一下你的数据请求方法让他累加上来

**Comment by VectorWen** [comment]
this.$waterfall.forceUpdate() 会让页面重新刷新。滚动的位置也不一样了
