### ISSUE TITLE
瀑布流loadmore问题

### ISSUE THREAD

**Issue by basonwoo** [AwesomeDevin/vue-waterfall2#63]
在A页面使用瀑布流组件，点击组件内容跳转到B页面的同时设置A页面keepAlive，在B页面向下滑动会触发A页面loadmore事件
A页面加载阶段如果内容撑满屏幕会自动触发loadmore

**Comment by AwesomeDevin** [comment]
keepAlive这个问题我看一下，自动触发的问题目前就是根据内容高度来判断的，不需要自动触发loadmore的话只能少加载点元素了
