### ISSUE TITLE
大佬 快看看这个单列问题吧

### ISSUE THREAD

**Issue by xts871722743** [AwesomeDevin/vue-waterfall2#65]
当这个瀑布流没渲染完的时候  快速切换到别的页面再切换回来就会出现只显示单列的问题

**Comment by AwesomeDevin** [comment]
请问这个问题是在什么环境下出现的？h5还是小程序里的webview组件

**Comment by xts871722743** [comment]
> 请问这个问题是在什么环境下出现的？h5还是小程序里的webview组件

公众号的项目，h5的这种。目前用强制刷新能解决掉。快速切换页面就会高度获取不到，源码里的判断也就进不去。所以就一列了
![image](https://user-images.githubusercontent.com/22048388/82815711-49fc2600-9ecc-11ea-9891-24a6893b66d6.png)

**Comment by AwesomeDevin** [comment]
ok,明白了

**Comment by AwesomeDevin** [comment]
你好，建议提供完整demo及说明vue版本号，因为我这边复现不了也不方便排查，感谢~
 邮箱号:awesomedevin@163.com
