### ISSUE TITLE
> 快速切换，会造成单列   

### ISSUE THREAD

**Issue by W-ChenAMG** [AwesomeDevin/vue-waterfall2#67]
快速切换，会造成单列，this.$waterfall.forceUpdate() 也没用

**Comment by smalike** [comment]
执行 `this.$waterfall.forceUpdate();`

**Comment by W-ChenAMG** [comment]
但是执行后，页面会重新强制刷新，那么之前缓存的滚动条高度啥 都没了 ，

**Comment by AwesomeDevin** [comment]
> 快速切换，会造成单列，this.$waterfall.forceUpdate() 也没用

你好，建议提供完整demo及说明vue版本号，因为我这边复现不了也方便排查，感谢~

**Comment by lzc991016** [comment]
> 但是执行后，页面会重新强制刷新，那么之前的缓存的滚动条高度啥都没有了，

这个有解决吗，遇到了相同问题
