### ISSUE TITLE
有时显示只一列问题

### ISSUE THREAD

**Issue by bepure1234** [AwesomeDevin/vue-waterfall2#70]
大佬，
![1595922200(1)](https://user-images.githubusercontent.com/38683983/88636330-53cc2080-d0eb-11ea-965d-bf322b504333.jpg)
![1595922223(1)](https://user-images.githubusercontent.com/38683983/88636369-62b2d300-d0eb-11ea-988d-0f57a35db81f.jpg)

有时默认只展示一列怎么解决

**Comment by AwesomeDevin** [comment]
你好，建议提供完整demo及说明vue版本号，因为我这边复现不了也方便排查，感谢~
 邮箱号:awesomedevin@163.com
