### ISSUE TITLE
加载图片过多的问题

### ISSUE THREAD

**Issue by Fros1er** [AwesomeDevin/vue-waterfall2#74]
如果一次性加载清晰度较高图片过多的话内存占用吃不住....
我目前的想法是在data数组过长的时候把前面的一部分删掉，但这样的话翻回去的时候没有对应的事件可以触发
请问能不能添加一个滑到顶端时触发的事件...

**Comment by AwesomeDevin** [comment]
目前 scroll() 事件，有提供滚动信息，业务侧是否可以通过滚动信息来判断是否滑到顶端
