### ISSUE TITLE
加急问题

### ISSUE THREAD

**Issue by wAdMaoMao** [AwesomeDevin/vue-waterfall2#8]
@AwesomeDevin 
Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at VueComponent.init (waterfall.vue?88a6:106)
    at eval (waterfall.vue?88a6:228)
样式正常显示，刷新页面会报错，偶尔不报错！尊敬的作者，请您尽快解决这个问题？上线项目，实在是着急！能提供一下您的联系方式吗?(我的联系方式 QQ 741350922)

**Comment by AwesomeDevin** [comment]
> appendChild

我这边排查一下~,稍等

**Comment by AwesomeDevin** [comment]
方便提供一下vue的版本号吗

**Comment by wAdMaoMao** [comment]
6.4.1




------------------ 原始邮件 ------------------
发件人: "Devin"<notifications@github.com>; 
发送时间: 2019年5月7日(星期二) 晚上7:17
收件人: "AwesomeDevin/vue-waterfall2"<vue-waterfall2@noreply.github.com>; 
抄送: "哆哆"<741350922@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AwesomeDevin/vue-waterfall2] 加急问题 (#8)




方便提供一下vue的版本号吗
