### ISSUE TITLE
您好，支持vue3吗？我试了 报错

### ISSUE THREAD

**Issue by xiaoForest** [AwesomeDevin/vue-waterfall2#86]
Uncaught TypeError: _vue2.default is not a constructor

**Comment by AwesomeDevin** [comment]
你好，还未支持

**Comment by loveshiguang** [comment]
你好 ， 啥时候开始支持呢？

**Comment by zouwenw** [comment]
你好，啥时候可以支持vue3项目呢

**Comment by AwesomeDevin** [comment]
这周末花时间跟一下

**Comment by AwesomeDevin** [comment]
vue-waterfall2@2.x 适用于 vue3, 如果你的应用是 vue2，请使用 vue-waterfall2@1.10.x, [1.10.x document](https://github.com/AwesomeDevin/vue-waterfall2/tree/1.10.6)
