### ISSUE TITLE
滚动到底部，loadmore未触发

### ISSUE THREAD

**Issue by AnneDong** [AwesomeDevin/vue-waterfall2#87]
![image](https://user-images.githubusercontent.com/20206950/100858302-c51c4580-34c8-11eb-8507-8146653d06c9.png)

**Comment by Ryannine** [comment]
未触发加1

**Comment by Adhders** [comment]
未触发加1

**Comment by AwesomeDevin** [comment]
可参考 https://github.com/AwesomeDevin/vue-waterfall2/issues/28
