### ISSUE TITLE
会出现某一列空白的情况

### ISSUE THREAD

**Issue by Yuzai-run** [AwesomeDevin/vue-waterfall2#88]
下拉加载时，会出现某一列大片空白现象

**Comment by Yuzai-run** [comment]
![image](https://user-images.githubusercontent.com/42103556/100957624-c5165700-3555-11eb-998a-802fd023b513.png)

**Comment by djy1342262996** [comment]
你好 请问您的解决了吗

**Comment by zhenlaile** [comment]
修改源码中的方法 直接设定图片高度就好了
