### ISSUE TITLE
页面返回控件回到顶部

### ISSUE THREAD

**Issue by fenghong007** [AwesomeDevin/vue-waterfall2#93]
当我从A页面（瀑布流页面）跳转到B页面后，再从B页面返回到A页面，发现A页面又回到顶部。

例子：我在A页面下拉到第三页，在第三页点击图片进入到图片详情B页面，再从B页面回到A页面时，发现A页面又回到顶部，没有保持在原来的位置。

测试了下发现：当设置height后会出现这种情况。

这个有解决方法吗？

**Comment by AwesomeDevin** [comment]
预测是组件重新渲染了，可以想办法阻止组件重新渲染应该就能解决
