### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read property '$scopedSlots' of undefined"

### ISSUE THREAD

**Issue by xiguatoufanzi** [AwesomeDevin/vue-waterfall2#94]
[Vue warn]: Error in nextTick: "TypeError: Cannot read property '$scopedSlots' of undefined"
TypeError: Cannot read property '$scopedSlots' of undefined
这是什么问题呢

**Comment by AwesomeDevin** [comment]
....没遇到过，需要信息再详细些
